[gcg]
src.git = "https://github.com/scipopt/gcg.git"
fetch.github = "scipopt/gcg"
git.leaveDotGit = true

[ipopt]
src.git = "https://github.com/coin-or/Ipopt.git"
fetch.github = "coin-or/Ipopt"

[mip-dd]
src.git = "https://github.com/scipopt/MIP-DD.git"
fetch.github = "scipopt/MIP-DD"

[mumps-harness]
src.git = "https://github.com/coin-or-tools/ThirdParty-Mumps.git"
fetch.github = "coin-or-tools/ThirdParty-Mumps"

[papilo]
src.git = "https://github.com/scipopt/papilo.git"
fetch.github = "scipopt/papilo"

[pygcgopt]
src.git = "https://github.com/scipopt/PyGCGOpt.git"
fetch.github = "scipopt/PyGCGOpt"

[pyscipopt]
src.git = "https://github.com/scipopt/PySCIPOpt.git"
fetch.github = "scipopt/PySCIPOpt"

[pysoplex]
src.git = "https://github.com/scipopt/PySoPlex.git"
fetch.github = "scipopt/PySoPlex"

[scip]
src.git = "https://github.com/scipopt/scip.git"
fetch.github = "scipopt/scip"
git.fetchSubmodules = true # nvfetcher produces wrong hash otherwise (even though we dont need the submodules)
git.leaveDotGit = true

[scippp]
src.git = "https://github.com/scipopt/SCIPpp.git"
fetch.github = "scipopt/SCIPpp"

[soplex]
src.git = "https://github.com/scipopt/soplex.git"
fetch.github = "scipopt/soplex"
git.fetchSubmodules = true # nvfetcher produces wrong hash otherwise (even though we dont need the submodules)
git.leaveDotGit = true

[vipr]
src.git = "https://github.com/scipopt/vipr.git"
fetch.github = "scipopt/vipr"

[zimpl]
src.git = "https://github.com/scipopt/zimpl.git"
fetch.github = "scipopt/zimpl"
