# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gcg = {
    pname = "gcg";
    version = "v360";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "gcg";
      rev = "v360";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-MRgsmP9LuTpS/FEPBNJSrIbYlUGh8EOEcbbl0MVEiRA=";
    };
  };
  papilo = {
    pname = "papilo";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "papilo";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-X6xr7nhTj5q8QJHn4AtUZSTyVusUDv5X4Dgv0bLf0kE=";
    };
  };
  pygcgopt = {
    pname = "pygcgopt";
    version = "6e2e51aabd11d3cb4ebdf79992c3618758801016";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PyGCGOpt";
      rev = "6e2e51aabd11d3cb4ebdf79992c3618758801016";
      fetchSubmodules = false;
      sha256 = "sha256-1nf5ctEBDR9ZFEOPcHFa+9qnytWkiydZaP8RZhG2XXY=";
    };
    date = "2024-03-08";
  };
  pyscipopt = {
    pname = "pyscipopt";
    version = "v5.0.1";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySCIPOpt";
      rev = "v5.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-zfebn7jhvDndWAn+eB0q+2iOjPIqY143bbaKePl4FSQ=";
    };
  };
  pysoplex = {
    pname = "pysoplex";
    version = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySoPlex";
      rev = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
      fetchSubmodules = false;
      sha256 = "sha256-8/bndwQ0aUSMl3XTZctfW3SH85IIrlCln6+9cQGuU9Q=";
    };
    date = "2024-02-27";
  };
  scip = {
    pname = "scip";
    version = "v900";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "scip";
      rev = "v900";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-mcCExe5lHmW2nTKbSXXifA9LIclru9LPlFG5Aj8K3+M=";
    };
  };
  scippp = {
    pname = "scippp";
    version = "1.1.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "SCIPpp";
      rev = "1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-3BsFUpPYMxVhqpaBfqtt/TJnqeRM94BLsMUdoA2Vk5E=";
    };
  };
  soplex = {
    pname = "soplex";
    version = "release-701";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "soplex";
      rev = "release-701";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-DSkIm1yD0z7ZcDFdugRMflxzMlm0EbyKW7ku+rnwmWs=";
    };
  };
}
